### PR TITLE
Issue #27: Changed values of tournament points rewarded for game result

### PR DESCRIPTION
**Pull request by tantauralus**
From august, 1st 2016 on new tournament point values are used:
Points for "BYE" changed from 4 to 6
Points for "WIN" changed from 2 to 3
Points for "modified win" (Timed or true tie) changed from 1 to 2
Points for "Los" stay the same

### CODE REVIEW

**Comment by Inermis2** [comment]
Also there is no Head to Head tiebreaker now.

**Comment by gereons** [comment]
> Points for "modified win" (Timed or true tie) changed from 1 to 2

Ties still only award 1 point.

**Comment by tantauralus** [comment]
Oops, gereons is right...mea culpa

**Comment by tantauralus** [comment]
Oops, gereons is right...mea culpa

**Pull request closed without merging**
